# Generated by Django 4.1 on 2022-08-07 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_joining', models.DateField(auto_created=True)),
                ('faculty_name', models.CharField(max_length=70)),
                ('designation', models.CharField(max_length=200)),
                ('employee_id', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.PositiveBigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
